"""add review model

Revision ID: 041b2e099d9c
Revises: 02e5bc308d46
Create Date: 2026-07-19 16:23:00.862342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041b2e099d9c'
down_revision = '02e5bc308d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_reviews_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_reviews_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
